Task of lesson-3 is done!
byIlusion/GB_GeekShop pull request #3
Opened 2021-01-26 10:02 UTC by byIlusion

Задания все выполнил.
Сделал загрузку в БД в контроллере из json (если БД пустая), изображения добавлял через админку, поэтому при импорте из json в БД пишутся только адреса картинок без реализации их загрузки (предполагается что они уже там есть).
Еще сделал для mainapp отдельный urls.py, где реализовал навигацию по категориям каталога.

2021-01-27 14:22 UTC, Vokler requested changes

2021-01-27 14:22 UTC, Vokler commented on mainapp/models.py
> +    name = models.CharField(verbose_name="Наименование товара", max_length=128)
Все отлично, замечаний к коду нет. Только маленькое к стилю - следите за тем, чтобы везде был единый стиль кавычек.

2021-01-27 14:22 UTC, Vokler commented on mainapp/views.py
> +    if len(context['categories']) == 0:
Хороший вариант с тем, что если ничего в БД нет, то загрузка идет из json.
Но обычно, если чего-то нет в БД, на сайте идет сообщение о том, что "Товаров на продажу пока-что нет" - ну что-то в таком духе.

Можете оставить то, как у вас. Можете изменить на предложенный вариант. На ваш выбор)
Но просто в реальных проектах, чем меньше логике в контроллере, тем лучше. На последнем уроке мы изучим CBV (Class-Based Views) и ваш кусок кода нужно будет тянуть и туда.

2021-01-28 02:32 UTC, byIlusion commented on mainapp/views.py
> +    if len(context['categories']) == 0:
Эта логика исключительно для тестового развертывания. В бою такой логики, естественно, не будет. Я не придумал как по-другому реализовать загрузку из JSON в БД кроме как в момент загрузки страницы товаров.

2021-01-28 03:50 UTC, byIlusion commented
Исправил ковычки в коде

2021-01-28 11:18 UTC, merged