Lesson 05
byIlusion/GB_GeekShop pull request #5
Opened 2021-02-02 14:45 UTC by byIlusion

Все сделал.
Но от вывода на форме авторизации сообщения о обязательных полях так и не избавился.
Возможно что-то не то с определением формы.

2021-02-04 12:00 UTC, Vokler requested changes

2021-02-04 12:00 UTC, vprinz commented on basketapp/models.py
> +    def stat(basket):
Боюсь, что вы не верно создали статический метод для класса. Первый аргумент должен быть класс _cls_, а потом уже аргументы. И не совсем понял, зачем тут статический метод? Можно было использовать обычный.

2021-02-04 12:00 UTC, Vokler commented on userapp/templates/userapp/login.html
> +                {{ form.errors|escape }}
Посмотрите тут про non_field_erros - их нужно использовать в форме авторизации. Скорее из-за этого у вас не совсем корректная работа с ошибками в авторизации
https://docs.djangoproject.com/en/3.1/ref/forms/api/#django.forms.Form.non_field_errors

2021-02-05 03:46 UTC, byIlusion commented on basketapp/models.py
> +    def stat(basket):
Давно не пользовался статическими методами, воссоздал по памяти. Когда подставил аргумент `cls`, то код отказался работать, т.к. Ожидалось принятие этого параметра. Потом погуглил и нашел что без аргумента `cls` тоже можно использовать - тогда это будет метод класса не привязанный к родительскому классу.
Для использования статического класса логика у меня была такая:

1. Статистика всей корзины пользователя связана с объектом корзины условно, т.е. запрос корзины все равно нужен (хотя у меня организовано так что использую уже имеющиеся данные по товарам корзины - всего 1 запрос в БД).
2. И для самого класса этот метод не важен, никакой логики для работы класса не содержит.
3. А в исходном классе только для того что его логично держать именно в этом классе, т.к. связан с корзиной.

2021-02-05 03:51 UTC, byIlusion commented on userapp/templates/userapp/login.html
> +                {{ form.errors|escape }}
Я разобрался с ошибками:
Я пытался вызывать форму с параметрами POST, даже если их еще не было (считал что на результат никак повлиять не должно):
`form = UserLoginForm(data=request.POST)`
Но когда переделал чтобы без POST-параметров загружалась форма без параметров:
`form = UserLoginForm(data=request.POST)`,
то все стало нормально.

2021-02-05 03:52 UTC, byIlusion commented
Поправил код немного. Под комментариями оставил свои заметки.

2021-02-05 09:25 UTC, Vokler commented on basketapp/models.py
> +    def stat(basket):
Хорошо, принимается!

2021-02-05 09:25 UTC, Vokler approved these changes

2021-02-05 09:26 UTC, merged