Completed
byIlusion/GB_GeekShop pull request #8
Opened 2021-02-13 07:04 UTC by byIlusion

Все сделал по заданию.
CBV удалось воткнуть только в adminapp, в другие приложения как-то не очень получилось, очень уж они замороченные.

2021-02-14 11:16 UTC, Vokler requested changes

2021-02-14 11:16 UTC, Vokler commented on adminapp/templates/adminapp/category.html
> +    <form method="post" enctype="multipart/form-data">
А почему вы убрали action? Без него форма не будет отправлена?

2021-02-14 11:16 UTC, Vokler commented on adminapp/views.py
> +    def get_success_url(self):
Этот метод необязательно создавать, можно просто передать success_url, как параметр класса

2021-02-15 13:31 UTC, byIlusion reviewed
Вернул атрибут action в форму категории.

2021-02-15 13:31 UTC, byIlusion commented on adminapp/views.py
> +    def get_success_url(self):
В success_url по моей задумке хотел передать текущий url страницы редактирования текущей категории, т.е. после обновления чтобы открывалась эта же страница.
`self.success_url = reverse_lazy('admin_staff:user_update', args=[self.kwargs['pk']])`
Этот адрес без id категории не сгенерить, а id возможно получить только из метода.

2021-02-15 14:10 UTC, merged